-- Helpers bypass recursive policy reads but expose only a boolean scoped to auth.uid().
create function public.org_staff(org uuid, writing boolean default false) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from organisation_members where organisation_id=org and profile_id=auth.uid() and (not writing or role in ('owner','manager'))) $$;
create function public.room_staff(room uuid, writing boolean default false) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from rooms r join properties p on p.id=r.property_id where r.id=room and org_staff(p.organisation_id,writing)) $$;
create function public.room_member(room uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships where room_id=room and profile_id=auth.uid() and status='active') $$;
create function public.own_membership(member uuid, room uuid default null) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships where id=member and profile_id=auth.uid() and status='active' and (room is null or room_id=room)) $$;
create function public.block_visible(block uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from content_blocks b where b.id=block and room_member(b.room_id) and b.published_snapshot->>'status'='published' and b.published_snapshot->>'visibility' in ('member','invitee','scheduled') and (b.published_snapshot->>'visibility'<>'scheduled' or (b.published_snapshot->>'visible_from')::timestamptz <= now())) $$;
create function public.repair_visible(request uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from maintenance_requests r where r.id=request and (room_staff(r.room_id) or own_membership(r.membership_id,r.room_id))) $$;
create function public.repair_staff(request uuid,writing boolean default false) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from maintenance_requests r where r.id=request and room_staff(r.room_id,writing)) $$;
create function public.repair_owner(request uuid,draft_only boolean default false) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from maintenance_requests r where r.id=request and own_membership(r.membership_id,r.room_id) and (not draft_only or status='draft')) $$;
create function public.property_staff(prop uuid, writing boolean default false) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from properties p where p.id=prop and org_staff(p.organisation_id,writing)) $$;
create function public.property_member(prop uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from rooms r where r.property_id=prop and room_member(r.id)) $$;
create policy profile_self on profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy organisations_read on organisations for select to authenticated using(org_staff(id) or created_by=auth.uid());
create policy organisations_insert on organisations for insert to authenticated with check(created_by=auth.uid());
create policy organisations_update on organisations for update to authenticated using(org_staff(id,true)) with check(org_staff(id,true));
create policy org_members_read on organisation_members for select to authenticated using(profile_id=auth.uid() or org_staff(organisation_id));
create policy org_members_bootstrap on organisation_members for insert to authenticated with check(profile_id=auth.uid() and role='owner' and exists(select 1 from organisations o where o.id=organisation_id and o.created_by=auth.uid()));
create policy properties_read on properties for select to authenticated using(org_staff(organisation_id) or property_member(id));
create policy properties_write on properties for all to authenticated using(org_staff(organisation_id,true)) with check(org_staff(organisation_id,true));
create policy rooms_read on rooms for select to authenticated using(room_staff(id) or room_member(id));
create policy rooms_write on rooms for all to authenticated using(room_staff(id,true)) with check(property_staff(property_id,true));
create policy memberships_read on memberships for select to authenticated using((profile_id=auth.uid() and status='active') or room_staff(room_id));
create policy memberships_update on memberships for update to authenticated using(own_membership(id)) with check(own_membership(id));
create policy invites_read on invites for select to authenticated using(room_staff(room_id));
create policy invites_insert on invites for insert to authenticated with check(room_staff(room_id,true) and created_by=auth.uid());
create policy invites_update on invites for update to authenticated using(room_staff(room_id,true)) with check(room_staff(room_id,true));
-- Working rows are never readable by residents. resident_content returns only the frozen snapshot.
create policy content_read on content_blocks for select to authenticated using(room_staff(room_id));
create policy content_write on content_blocks for all to authenticated using(room_staff(room_id,true)) with check(room_staff(room_id,true));
create policy versions_read on content_versions for select to authenticated using(exists(select 1 from content_blocks b where b.id=content_block_id and room_staff(b.room_id)));
create policy versions_insert on content_versions for insert to authenticated with check(changed_by=auth.uid() and exists(select 1 from content_blocks b where b.id=content_block_id and room_staff(b.room_id,true)));
create policy translations_read on translations for select to authenticated using(exists(select 1 from content_blocks b where b.id=content_block_id and room_staff(b.room_id)));
create policy translations_write on translations for all to authenticated using(exists(select 1 from content_blocks b where b.id=content_block_id and room_staff(b.room_id,true))) with check(exists(select 1 from content_blocks b where b.id=content_block_id and room_staff(b.room_id,true)));
create function public.ack_allowed(member uuid,block uuid,v integer) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from content_blocks b where b.id=block and own_membership(member,b.room_id) and block_visible(block) and b.published_version=v and (b.published_snapshot->>'required_acknowledgement')::boolean) $$;
create policy ack_read on acknowledgements for select to authenticated using(own_membership(membership_id) or exists(select 1 from memberships m where m.id=membership_id and room_staff(m.room_id)));
create policy ack_insert on acknowledgements for insert to authenticated with check(ack_allowed(membership_id,content_block_id,content_version));
create policy tasks_read on onboarding_tasks for select to authenticated using(room_staff(room_id) or room_member(room_id));
create policy tasks_write on onboarding_tasks for all to authenticated using(room_staff(room_id,true)) with check(room_staff(room_id,true));
create policy completion_read on onboarding_task_completions for select to authenticated using(own_membership(membership_id));
create policy completion_insert on onboarding_task_completions for insert to authenticated with check(exists(select 1 from onboarding_tasks t where t.id=onboarding_task_id and own_membership(membership_id,t.room_id) and t.completion_kind<>'manager_confirmed'));
create policy questions_read on question_logs for select to authenticated using(own_membership(membership_id,room_id) or room_staff(room_id));
create policy questions_insert on question_logs for insert to authenticated with check(own_membership(membership_id,room_id));
create policy questions_feedback on question_logs for update to authenticated using(own_membership(membership_id,room_id)) with check(own_membership(membership_id,room_id));
create policy runs_read on ai_runs for select to authenticated using(room_staff(room_id) or actor_id=auth.uid());
create policy runs_insert on ai_runs for insert to authenticated with check(actor_id=auth.uid() and (room_staff(room_id,true) or (room_member(room_id) and purpose in ('answer','maintenance_triage'))) and exists(select 1 from rooms r join properties p on p.id=r.property_id where r.id=room_id and p.organisation_id=ai_runs.organisation_id));
create policy suggestions_manage on ai_suggestions for all to authenticated using(room_staff(room_id,true)) with check(room_staff(room_id,true));
create policy repair_read on maintenance_requests for select to authenticated using(room_staff(room_id) or own_membership(membership_id,room_id));
create policy repair_insert on maintenance_requests for insert to authenticated with check(own_membership(membership_id,room_id) and status='draft');
create policy repair_update on maintenance_requests for update to authenticated using(room_staff(room_id,true) or own_membership(membership_id,room_id)) with check(room_staff(room_id,true) or own_membership(membership_id,room_id));
create policy attachment_read on maintenance_attachments for select to authenticated using(repair_visible(maintenance_request_id));
create policy attachment_insert on maintenance_attachments for insert to authenticated with check(repair_owner(maintenance_request_id,true) and storage_path like auth.uid()::text||'/'||maintenance_request_id::text||'/%');
create policy events_read on maintenance_events for select to authenticated using(repair_staff(maintenance_request_id) or (resident_visible and repair_owner(maintenance_request_id)));
create policy events_insert on maintenance_events for insert to authenticated with check(actor_id=auth.uid() and (repair_staff(maintenance_request_id,true) or (repair_owner(maintenance_request_id) and event_type='submitted' and resident_visible)));
create policy onboarding_own on manager_onboarding for all to authenticated using(profile_id=auth.uid()) with check(profile_id=auth.uid());
grant usage on schema public to authenticated,anon;
grant select,insert,update on all tables in schema public to authenticated;
revoke update on content_versions,acknowledgements,onboarding_task_completions,maintenance_events,ai_runs from authenticated;
-- No delete grants: archive and immutable history are intentional.
create function public.resident_content() returns setof jsonb language sql stable security definer set search_path=public as $$ select b.published_snapshot || jsonb_build_object('id',b.id,'room_id',b.room_id,'created_at',b.created_at,'updated_at',b.updated_at,'published_snapshot',b.published_snapshot,'published_version',b.published_version) from content_blocks b where block_visible(b.id) $$;
-- Small authorised corpus, full-text ranking plus title/key boosts, no embeddings.
create function public.search_home_content(room uuid,question text) returns setof jsonb language sql stable security definer set search_path=public as $$ select b.published_snapshot || jsonb_build_object('id',b.id) from content_blocks b where b.room_id=room and block_visible(b.id) and (to_tsvector('simple',coalesce(b.published_snapshot->>'title','')||' '||coalesce(b.published_snapshot->>'body','')) @@ plainto_tsquery('simple',question) or b.published_snapshot->>'title' ilike '%'||question||'%') order by ts_rank(to_tsvector('simple',coalesce(b.published_snapshot->>'title','')||' '||coalesce(b.published_snapshot->>'body','')),plainto_tsquery('simple',question)) + case when b.published_snapshot->>'title' ilike '%'||question||'%' then 2 else 0 end desc limit 8 $$;
